In [37]:
# compare the for loop and matrix computing
import numpy as np
import time

In [29]:
a = np.random.rand(1000000)
b = np.random.rand(1000000, 1000)
a.shape
b.shape

(1000000, 1000)

In [34]:
res = np.zeros(1000, dtype=int)
for i in range (b.shape[1]):
    tmp = 0
    for j in range(a.shape[0]):
        tmp += a[j] * b[j][i]
    res[i] += tmp

In [45]:
res;

In [39]:
res = np.dot(a.reshape(1000000, 1).T, b)

In [44]:
res.astype(int);

In [46]:
A = np.array([[56.0, 0.0, 4.4, 68.0],[1.2, 104.0, 52.0, 8.0], [1.8, 135.0, 99.0, 0.9]])

In [51]:
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [50]:
A / A.sum(axis=0)

array([[0.94915254, 0.        , 0.02831403, 0.88426528],
       [0.02033898, 0.43514644, 0.33462033, 0.10403121],
       [0.03050847, 0.56485356, 0.63706564, 0.01170351]])

In [52]:
A + 1

array([[ 57. ,   1. ,   5.4,  69. ],
       [  2.2, 105. ,  53. ,   9. ],
       [  2.8, 136. , 100. ,   1.9]])

In [53]:
A + [1, 2, 3, 4]

array([[ 57. ,   2. ,   7.4,  72. ],
       [  2.2, 106. ,  55. ,  12. ],
       [  2.8, 137. , 102. ,   4.9]])

In [54]:
a = np.random.randn(5); a

array([ 0.04796176, -1.63739809,  0.28608941, -0.12048416, -1.47591191])

In [55]:
a.shape

(5,)

In [56]:
np.dot(a, a.T)

4.958052367384842

In [57]:
np.dot(a.T, a)

4.958052367384842

In [60]:
a = np.random.randn(1, 5); a

array([[-0.42505129,  0.66032712,  0.67220678,  1.36258666, -0.6514545 ]])

In [61]:
a.T

array([[-0.42505129],
       [ 0.66032712],
       [ 0.67220678],
       [ 1.36258666],
       [-0.6514545 ]])

In [62]:
np.dot(a.T, a)

array([[ 0.1806686 , -0.28067289, -0.28572236, -0.57916921,  0.27690158],
       [-0.28067289,  0.43603191,  0.44387637,  0.89975293, -0.43017308],
       [-0.28572236,  0.44387637,  0.45186195,  0.91593999, -0.43791213],
       [-0.57916921,  0.89975293,  0.91593999,  1.85664241, -0.88766322],
       [ 0.27690158, -0.43017308, -0.43791213, -0.88766322,  0.42439297]])