In [8]:
# define the MyDataSet

import torch
from torch.utils import data



class MyDataset(torch.utils.data.Dataset):
    def __init__(self):
        # initial the data. If the data is a image and target, we need to transfer the site
        self.data = torch.arange(0, 20)
    
    def __getitem__(self, index):
        # get the item from data set
        x = self.data[index]
        y = x * 2
        return y
    
    def __len__(self):
        return len(self.data)

# define dataloader
dataset = MyDataset()
print(len(dataset))
print(dataset[3]) # the __getitem__ modify the index method about this dataset


# if the data set / batch_size is not satisfy?


dataloader = torch.utils.data.DataLoader(dataset, shuffle=True, batch_size=5)
print(len(dataloader))

for x in dataloader:
    print(x)

20
tensor(6)
4
tensor([ 4,  6, 14, 12, 30])
tensor([ 2, 32, 18, 38, 20])
tensor([ 8, 34, 24, 10, 36])
tensor([16,  0, 26, 28, 22])
