In [1]:
import torch 

x = torch.tensor([3, 0])
y = torch.tensor([2, 0])


In [2]:
x

tensor([3, 0])

In [3]:
x[1]

tensor(0)

In [4]:
len(x)

2

In [5]:
x.shape # 长度固定的一个列表

torch.Size([2])

In [6]:
A = torch.arange(20).reshape(5, 4)
B = torch.arange(20).reshape(4, 5)



In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [8]:
# 维度都可以随意改变
X = torch.arange(24).reshape(2, 3, 4)

In [9]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [10]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # clone 不是简单引用
id(A), id(B)

# 使用clone 完成了深度copy

(1860313144672, 1860324171584)

In [11]:
# 和 numpy类似 会进行适当的扩散 broadcast
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape


(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [12]:
X.sum(axis=0)

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [13]:
A = torch.arange(20 * 2 ).reshape(2, 5, 4)

In [14]:
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780))

In [15]:
A.shape[1]

5

In [16]:
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [17]:
A.sum(axis=0)

tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

In [18]:
torch.cuda.is_available()

False

In [19]:
A.sum(axis=[0, 1])

tensor([180, 190, 200, 210])

In [20]:
A.numel()

40

In [21]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[[ 40,  45,  50,  55]],

        [[140, 145, 150, 155]]])

In [22]:
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [23]:
A.shape, x.shape

(torch.Size([2, 5, 4]), torch.Size([2]))

In [24]:
from functools import reduce
size = reduce(lambda x, y: x * y, list(A.shape))

A = A.reshape((size // 2, 2))
A.shape
# mv -- matrix * vector

torch.mv(A, x)

tensor([  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,  78,
         84,  90,  96, 102, 108, 114])

In [25]:
A = torch.arange(20).reshape((4, 5))
B = torch.arange(20).reshape((5, 4))
A, B, torch.mm(A, B)

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[120, 130, 140, 150],
         [320, 355, 390, 425],
         [520, 580, 640, 700],
         [720, 805, 890, 975]]))

In [26]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [27]:
torch.abs(u).sum()

tensor(7.)

In [28]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [29]:
a = torch.ones((2, 5, 4))
a.shape

torch.Size([2, 5, 4])

In [30]:
a.sum(axis=1).shape

torch.Size([2, 4])

In [31]:
a.sum(axis=[0, 2], keepdim=True).shape

torch.Size([1, 5, 1])

In [32]:
a.sum(axis=[0, 2]).shape

torch.Size([5])

In [33]:
x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [34]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [35]:
y.backward()

In [36]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [37]:
x.grad == 4 * x

tensor([True, True, True, True])

In [38]:
# x.grad.zero_()

In [39]:
# 因为缓存 一些奇怪的事情发生了
y = x * x
y.sum().backward()
x.grad

tensor([ 0.,  6., 12., 18.])

In [40]:
# eliminate the previous gradient
x.grad.zero_()
y = x * x
u = y.detach() # u 现在是一个标量了
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [41]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [42]:
# 如果遇到了复杂的python控制流 也可以做这些事 
# 因为backward() 会记录下你的这些操作 就像一棵树 触发则生成
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() >  0:
        c = b
    else: 
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d / a

tensor(True)

In [43]:
a.grad

tensor(4096.)

In [46]:
torch.cuda.is_available()

False

In [44]:
!python --version

Python 3.8.0
